version: '3.4'

networks: 
  keycloak-net:

volumes:
  keycloak-datastore:

services:
  keycloak-db:
    image: postgres:9.6
    volumes:
      - /home/anon/keycloak-datastore:/var/lib/postgresql/data
    networks:
      - keycloak-net
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB:   keycloak
      POSTGRES_USER:     keycloak
      POSTGRES_PASSWORD: keycloak_pw
  
  keycloak:
    # image: jboss/keycloak:4.8.3.Final
    # image: custom/keycloak:test
    image: block360/keycloak
    depends_on:
      - keycloak-db
    networks:
      - keycloak-net
    ports:
      - "8180:8080"
    # volumes:
      # - /home/anon/workspaces/block360/custom:/opt/jboss/keycloak

      # - /home/anon/workspaces/block360/custom-auth/beercloak/beercloak-ear/target:/opt/jboss/keycloak/standalone/deployments
    environment:
      DB_VENDOR:   POSTGRES
      DB_ADDR:     keycloak-db
      DB_PORT:     5432
      DB_DATABASE: keycloak
      DB_USER:     keycloak
      DB_PASSWORD: keycloak_pw
      KEYCLOAK_USER:     admin
      KEYCLOAK_PASSWORD: admin


